[package]
name = "jonhdope/jecs-fluid"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
description = "slightly edited version of jecs-vide to work with fluid"
include = [
    "default.project.json",
    "dist",
    "dist/**",
    "LICENSE",
    "wally.toml",
    "README.md",
    ".luaurc",
]

[dependencies]
fluid = "ffrostfall/fluid@0.6.4"
jecs = "ukendio/jecs@0.9.0"
jecs-utils = "pepeeltoro41/jecs-utils@1.1.1"